version: 2.1

jobs:
  deploy_app_to_railway:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Install Railway CLI
          command: npm install -g @railway/cli
      - run:
          name: Login to Railway
          command: |
            if [ -z "$RAILWAY_TOKEN" ]; then
              echo "RAILWAY_TOKEN no definido en CircleCI"; exit 1
            fi
            railway login --token "$RAILWAY_TOKEN"
      - run:
          name: Deploy to Railway
          command: |
            SERVICE_NAME="giving-stillness"  # <-- cámbialo
            railway up --service="${SERVICE_NAME}" --no-confirm

workflows:
  build-and-deploy:
    jobs:
      - deploy_app_to_railway:
          filters:
            branches:
              only: main
